In [1]:
n = input().split()
s = 0
for i in n:
    a = len(i)//2
    s += int(i[a])
print(s)

987 651 234
16


# Data-Analysis-Using-Python  

<ol>
    <li>Any useful information is called as data</li>
    <br>
    <li>Types of data in devices</li>
    <ul>
        <li>.txt</li>
        <li>.img</li>
        <li>.ppt</li>
        <li>.mp3</li>
        <li>.csv</li>
        <li>.excel</li>
    </ul>
    <br>
    <li>Types of Data In real Time</li>
    <ol> 
        <li>Quantitative data</li>
        <ul> 
            <li>Represents the size/volume of data.</li>
            <li>Discrete and Continous</li>
            <li>Discrete : Data is constant/fixed</li> 
            <li>   Ex: numbers in a dice,color,nationality etc.</li>
            <li>Continous data means the value/Data is continous. </li>
            <li>   Ex: time,height,weight </li>
        </ul>
        <li>Qualitative data </li>
        <ul> 
            <li>Data is analyed and categorised</li>
            <li>   Ex: Data submission in feedback form.</li>
        </ul>
    </ol>
    <br>
    <li> Data in statistics</li>
    <ol> 
        <li>Nominal, Ordinal, Interval and ratio</li>
        <ul> 
            <li>Nominal means data is categorized on the basics of names</li>
            <li>   Ex: color,Nationality,Gender </li>
            <li>Original means data</li>
        </ul>
    </ol>
</ol>

In [2]:
import numpy as np 
import pandas as pd 

import warnings 
warnings.filterwarnings('ignore')

In [3]:
np.__version__

'1.20.1'

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

## numpy means nuerical python
## which is used to deal with arrary ans scienific
## computation 
## array():- methode to create

In [5]:
a = np.array([1,2,3,4,5,6,8])
a

array([1, 2, 3, 4, 5, 6, 8])

In [6]:
b=np.array([1,2,3,4,5],dtype="float") # can be any datatype - int, str ..etc
b

array([1., 2., 3., 4., 5.])

## print array from 1 to 10 using range method

In [7]:
c = np.array(range(1,10))
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#print array from 1 to 50 skip by 2 
d = np.array(range(1,51,2))
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [9]:
#print array from 100 to 50 
d = np.array(range(100,49,-1))
d

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50])

## Basic methods in numpy array 

In [10]:
a.ndim

1

In [11]:
a = np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
a.ndim

2

In [13]:
a.size

6

In [14]:
a.shape

(2, 3)

In [15]:
a.dtype

dtype('int32')

In [16]:
d.flatten

<function ndarray.flatten>

In [17]:
a = np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,7,8]]])
a

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 7, 8]]])

In [18]:
a.ndim

3

In [19]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [20]:
a.ndim

1

In [21]:
a[0],a[1],a[2]

(1, 2, 3)

In [22]:
a = np.array([[2,3,4],[1,2,3]])
a

array([[2, 3, 4],
       [1, 2, 3]])

In [23]:
a.ndim

2

In [24]:
a[0],a[1]

(array([2, 3, 4]), array([1, 2, 3]))

In [25]:
a[0][1]

3

## n-dimensional arrays

In [26]:
a = np.array([1,2,3,4],ndmin=3)
a

array([[[1, 2, 3, 4]]])

In [27]:
a = np.eye(4,dtype = int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [28]:
a = np.zeros((3,3),dtype = int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
a = np.ones((3,2),dtype = int)
a

array([[1, 1],
       [1, 1],
       [1, 1]])

In [30]:
a = np.full((4,4),'hey!')
a

array([['hey!', 'hey!', 'hey!', 'hey!'],
       ['hey!', 'hey!', 'hey!', 'hey!'],
       ['hey!', 'hey!', 'hey!', 'hey!'],
       ['hey!', 'hey!', 'hey!', 'hey!']], dtype='<U4')

In [31]:
a.fill(4)
a

array([['4', '4', '4', '4'],
       ['4', '4', '4', '4'],
       ['4', '4', '4', '4'],
       ['4', '4', '4', '4']], dtype='<U4')

In [32]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## print array using arange method 
## start range = 20 
## end range = 100
## skip by 3 numbers

In [33]:
a = np.arange(20,100,3)
a

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

## Print array using arange method from 100 to 1 

In [34]:
a = np.arange(100,0,-1)
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

## Constructing 2d array from 1d array

In [35]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a.reshape(3,4) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a = np.arange(200)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [38]:
a.reshape(50,4)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59],
       [ 60,  61,  62,  63],
       [ 64,  65,  66,  67],
       [ 68,  69,  70,  71],
       [ 72,  73,  74,  75],
       [ 76,  77,  78,  79],
       [ 80,  81,  82,  83],
       [ 84,  85,  86,  87],
       [ 88,  89,  90,  91],
       [ 92,  93,  94,  95],
       [ 96,  97,  98,  99],
       [100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 1

## Random method - Numpy

In [39]:
a = np.random.randint(10)
a

8

In [40]:
b = np.array([np.random.randint(10) for i in range(1,100)])
b

array([5, 9, 4, 5, 6, 1, 8, 9, 9, 6, 3, 9, 7, 0, 2, 9, 2, 6, 4, 0, 4, 0,
       1, 1, 5, 0, 5, 9, 2, 8, 7, 5, 5, 4, 0, 3, 5, 6, 5, 1, 7, 9, 5, 0,
       4, 9, 8, 1, 6, 3, 0, 2, 8, 5, 6, 3, 2, 6, 4, 9, 9, 1, 2, 0, 9, 6,
       2, 8, 7, 5, 4, 2, 9, 4, 4, 2, 6, 9, 2, 7, 3, 4, 4, 1, 2, 1, 5, 6,
       5, 3, 5, 2, 1, 5, 9, 0, 4, 5, 5])

In [41]:
b.reshape(33,3)

array([[5, 9, 4],
       [5, 6, 1],
       [8, 9, 9],
       [6, 3, 9],
       [7, 0, 2],
       [9, 2, 6],
       [4, 0, 4],
       [0, 1, 1],
       [5, 0, 5],
       [9, 2, 8],
       [7, 5, 5],
       [4, 0, 3],
       [5, 6, 5],
       [1, 7, 9],
       [5, 0, 4],
       [9, 8, 1],
       [6, 3, 0],
       [2, 8, 5],
       [6, 3, 2],
       [6, 4, 9],
       [9, 1, 2],
       [0, 9, 6],
       [2, 8, 7],
       [5, 4, 2],
       [9, 4, 4],
       [2, 6, 9],
       [2, 7, 3],
       [4, 4, 1],
       [2, 1, 5],
       [6, 5, 3],
       [5, 2, 1],
       [5, 9, 0],
       [4, 5, 5]])

In [42]:
a = np.random.randint(7,100,10)
a.reshape(2,5)

array([[11, 40, 45, 26, 31],
       [87, 86, 84, 87, 37]])

In [43]:
c = np.random.rand(4,3)
c

array([[0.49960107, 0.65356855, 0.88581491],
       [0.7294107 , 0.91092029, 0.48349592],
       [0.44504566, 0.40511492, 0.44787108],
       [0.3357983 , 0.75118186, 0.98770471]])

## Linspace

In [46]:
a = np.linspace(1,1,dtype = int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [47]:
b = np.arange(20).reshape(4,5)
print(b)
print(b.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


## Accessing subarray from main array

In [48]:
a = np.arange(10).reshape(2,5)
print(a)
print(a[0,0:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1]


In [49]:
a = np.arange(10).reshape(2,5)
print(a)
print(a[1,1:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[6 7]


## ARITHEMATIC Operations using numpy

In [52]:
a,b =np.arange(6),np.arange(6,12)
print(a,'\n',b)
x = a+b
y = a-b
z = a*b
w = a//b

print(x,y,z,w,sep='\n')

[0 1 2 3 4 5] 
 [ 6  7  8  9 10 11]
[ 6  8 10 12 14 16]
[-6 -6 -6 -6 -6 -6]
[ 0  7 16 27 40 55]
[0 0 0 0 0 0]


## Synthetic operations using numpy

In [50]:
np.log([1,2,3,4])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [51]:
np.sin([1,2,3,4])

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Statistics

In [53]:
a = np.array([[1,23,78],[20,40,60]])
print(a)

[[ 1 23 78]
 [20 40 60]]


In [54]:
print(np.amin(a))
print(np.amax(a))

1
78


In [55]:
a = np.array([5,6,7])
print(np.mean(a))

6.0


In [56]:
print(np.median(a))

6.0


## Standard deviation
## square root of average of square  

In [58]:
print(np.std(a))

0.816496580927726


## varaince 
## average of squares of standard deviation

In [60]:
print(np.var(a))

0.6666666666666666


## Aggregation

In [62]:
np.sum(a)

18

In [63]:
np.average(a)

6.0

In [64]:
np.prod(a)

210

In [67]:
np.minimum(a,np.array([2,3,4]))

array([2, 3, 4])

## Filtering 

In [69]:
a = np.array([42,43,44,45])
a

array([42, 43, 44, 45])

In [73]:
f=a>42
f

array([False,  True,  True,  True])

In [72]:
a[f]

array([43, 44, 45])

In [76]:
b = np.array([2,3,4,5,6,7,8,9])
b[b%2==0]

array([2, 4, 6, 8])

## Saving the data 

In [78]:
from numpy import asarray
from numpy import savetxt
data = np.array([[1,2,3,4],[4,5,6,7]])
savetxt('data.csv',data,delimiter=",")

## Display Data from .csv file

In [80]:
from numpy import loadtxt
data = loadtxt('data.csv',delimiter=',')
data

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])